#ifndef LIBSSH2_CONFIG_H
#define LIBSSH2_CONFIG_H

#define HAVE_SYS_SOCKET_H
#define HAVE_NETINET_IN_H
#define HAVE_SYS_SELECT_H
#define HAVE_UNISTD_H
#define HAVE_ARPA_INET_H
#define HAVE_SYS_TIME_H
#define HAVE_STDLIB_H

#endif //LIBSSH2_CONFIG_H